server:
  port: 8085
  servlet:
    context-path: /user-service
  compression:
    enabled: true
    min-response-size: 10
spring:
  application:
    name: hello-user-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848