### 注册
POST http://localhost:8080/auth/register
Content-Type: application/json
Accept: */*

{
  "username": "hello",
  "password": "123",
  "address":  "BJS"
}


### 登录
POST http://localhost:8080/auth/login
Content-Type: application/json
Accept: */*

{
  "username": "hello",
  "password": "123"
}


### 根据token 查询用户信息
GET http://localhost:8080/hello-gateway/user-service/auth/findByToken
Accept: */*
x-token: 723401211d3a4024b7a0accaac47c6fd