### 注册
POST http://localhost:8080/auth/register
Content-Type: application/json
Accept: */*

{
  "username": "hello",
  "password": "123",
  "address":  "BJS"
}


### 登录
POST http://localhost:8080/auth/login
Content-Type: application/json
Accept: */*

{
  "username": "hello",
  "password": "123"
}


### 根据token 查询用户信息
GET http://localhost:8080/hello-gateway/user-service/auth/findByToken
Accept: */*
x-token: 1e1e43c8a3074731806bb466b0c00194


### 根据token 查询用户信息
GET http://localhost:8080/hello-gateway/user-service/hello/index
Accept: */*
x-token: b12f476f6d5146548dd5b175e097877c