### 缓存body
GET http://localhost:8080/hello-webmvc/hello/index


### 缓存body
POST http://localhost:8080/hello-webmvc/hello/downstream
Content-Type: application/json

{
  "username": "yicj",
  "address": "bjs"
}

### 调用nacos-cliet微服务
GET http://localhost:8080/hello-gateway/hello-nacos-client/hello/index

