spring:
  application:
    name: gateway-app
server:
  port: 8080
  # 注意在gateway中配置context-path不生效
  servlet:
    context-path: /hello-gateway
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    # 重点在这里,默认为false,所以没有gateway相关端点,打开后就可以访问
    gateway:
      enabled: true
logging:
  level:
    root: info
    org.springframework.cloud.gateway: debug
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    org.springframework.boot.autoconfigure.web: debug
    reactor.netty: debug
