# 将这段配置放入nacos配置文件gateway-app.yaml中，可以实现动态路由效果
spring:
  cloud:
    gateway:
      routes:
        - id: add_request_parameter_route
          uri: https://example.org
          predicates:
            - Path=/add_request_parameter_route
          filters:
            - name: Custom
              args:
                message: My Custom Message
                preLogger: true
                postLogger: true
            - AddRequestParameter=red, blue
            - AddResponseHeader=X-Response-Red, Blue
            - StripPrefix=1
        - id: user_login
          uri: http://localhsot:8080
          predicates:
            - Path=/auth/login
          filters:
            - AddRequestParameter=red, blue
        - id: user_register
          uri: http://localhsot:8080
          predicates:
            - Path=/auth/register
          filters:
            - AddRequestParameter=red, blue
      discovery:
        locator:
          enabled: false # 这里设置为ture后服务无法访问
feign:
  httpclient:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 30000