# 将这段配置放入nacos配置文件gateway-app.yaml中，可以实现动态路由效果
spring:
  cloud:
    gateway:
      routes:
        - id: user_login
          uri: http://localhsot:8080
          predicates:
            - Path=/auth/login
          filters:
            - AddRequestParameter=red, blue
        - id: user_register
          uri: http://localhsot:8080
          predicates:
            - Path=/auth/register
          filters:
            - AddRequestParameter=red, blue
        - id:  hello-user-service
          uri: lb://hello-user-service
          predicates:
            - Path=/hello-gateway/user-service/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: false # 这里设置为ture后服务无法访问