# 这个地方独立配置, 是网关的数据, 代码 GatewayConfig.java 中读取被监听
nacos:
  gateway:
    route:
      config:
        namespace: hello-spring-cloud
        group: DEFAULT_GROUP
        data-id: hello-gateway-router.json