spring:
  cloud:
    gateway:
      routes:
        - id: nacos-client-app
          uri: lb://nacos-client-app
          predicates:
            - Path=/hello-gateway/hello-nacos-client/**
          filters:
            - StripPrefix=2
#        - id: nacos-client-app
#          uri: http://localhost:8081
#          predicates:
#            - Path=/hello-gateway/hello-nacos-client/**
#          filters:
#            - StripPrefix=2