server:
  port: 8086
spring:
  application:
    name: hello-kafka-app
  kafka:
    bootstrap-servers: 192.168.99.51:9092

# 暴露端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always