server:
  port: 8084
logging:
  level:
    root: info
spring:
  application:
    name: hello-webflux
  webflux:
    base-path: /hello-webflux
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848