server:
  port: 8086
spring:
  application:
    name: hello-circuit-breaker
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 50
  timelimiter:
    configs:
      default:
        timeoutDuration: 5s
        cancelRunningFuture: true