server:
  port: 8086
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.99.51:9092
          replication-factor: 1
        bindings:
          greetings-in:
            destination: greetings
            contentType: application/json
          greetings-out:
            destination: greetings
            contentType: application/json


