### rest template hello index
GET http://localhost:8082/hello-sentinel-client/feignClient/hello/index

### rest template hello exception
GET http://localhost:8082/hello-sentinel-client/feignClient/hello/exception