### 注册
POST http://localhost:8085/user-service/auth/register
Content-Type: application/json
Accept: */*

{
  "username": "hello",
  "password": "123",
  "address":  "BJS"
}


### 登录
POST http://localhost:8085/user-service/auth/login
Content-Type: application/json
Accept: */*

{
  "username": "hello",
  "password": "123"
}


### 根据token 查询用户信息
GET http://localhost:8085/user-service/auth/findByToken
Accept: */*
token: 679cfe76d09b4215b47a23be16c22a84

