server:
  port: 8083
  servlet:
    context-path: /hello-webmvc
management:
  endpoints:
    web:
      exposure:
        include: '*'
context:
  listener:
    classes: com.yicj.study.mvc.component.MyApplicationListener
